remote_theme: pmarsceill/just-the-docs
title: CS-1030 with Ruiz
description: Python3 references
logo: 'assets/images/ruiz.jpeg'

# Upper right navigation links
aux_links:
  "Python Language Reference": "https://docs.python.org/3/reference/index.html"
  "Python Tutor (Visualizer)": "http://www.pythontutor.com/visualize.html#mode=edit"
aux_links_new_tab: true

# Footer content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 Bianca Ruiz. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


  
  
