remote_theme: pmarsceill/just-the-docs
title: CS-1030 with Ruiz
description: Python3 references
logo: 'assets/images/ruiz.jpeg'
baseurl: "/CS-1030-with-Ruiz"

# Upper nav links
aux_links:
  "Python Language Reference": "https://docs.python.org/3/reference/index.html"
  "Python Tutor (Visualizer)": "http://www.pythontutor.com/visualize.html#mode=edit"
  "Repl.it Online IDE": "https://repl.it/"
aux_links_new_tab: true

# pages included in page navigation and search
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Footer on every page
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 Bianca Ruiz. Distributed by an <a href=\"https://github.com/CS-1030/CS-1030.github.io/tree/master/LICENSE.txt\">MIT license.</a>"

