remote_theme: pmarsceill/just-the-docs
title: CS-1030 with Ruiz
description: Python3 references
url: "https://cs-1030.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Upper nav links
aux_links:
  "Python Language Reference": "https://docs.python.org/3/reference/index.html"
  "Python Tutor (Visualizer)": "http://www.pythontutor.com/visualize.html#mode=edit"
  "Repl.it Online IDE": "https://repl.it/"
aux_links_new_tab: true

# pages included in page navigation and search
include:
  - _pages

# Footer on every page
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 Bianca Ruiz. Distributed by an <a href=\"https://github.com/CS-1030/CS-1030.github.io/tree/master/LICENSE.txt\">MIT license.</a>"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
