remote_theme: pmarsceill/just-the-docs
title: CS-1030 with Ruiz
description: Python3 references
logo: 'assets/images/ruiz.jpeg'
aux_links:
  "Python Language Reference": "https://docs.python.org/3/reference/index.html"
  "Python Tutor (Visualizer)": "http://www.pythontutor.com/visualize.html#mode=edit"
  
  
